name = "mcp-korea-weather"
main = "src/workers.ts"
compatibility_date = "2025-08-30"

[vars]
# 한국 기상청 API 설정
KMA_API_BASE_URL = "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
DEFAULT_PAGE_NO = "1"
DEFAULT_NUM_OF_ROWS = "100"
DEFAULT_DATA_TYPE = "JSON"